### ISSUE TITLE
Better solution for Changes.txt

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-distribution#10]
With the 3.5 release, the changes.txt file wasn't updated at first, and the question came up as to whether that was even a useful file to have.

I suggest we scrap it, it's too error prone. If we think there's a use for having a text contents, we could autogenerate something, showing the package versions included?

Alternatively, if we want to keep it, we should automate it.

**Comment by rprouse** [comment]
My vote would be to scrap it.

**Comment by CharliePoole** [comment]
Where do people get to see what release versions of each component are in each distribution?

**Comment by rprouse** [comment]
That is a good point. I wouldn't want to be manually updating a Wiki page. We could probably auto-generate a text file from the Cake build.

**Comment by ChrisMaddock** [comment]
Yes, that, or on the assembly versions. I couldn't decide if that was enough on it's own or not.
