### ISSUE TITLE
Update Appveyor webhook

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-distribution#14]
The Appveyor CI has now been moved to the main account - @rprouse or @CharliePoole - can one of you update where the webhook points to for this repo? 

The new link is: https://ci.appveyor.com/api/github/webhook?id=1r1f89j2mw6hahb6

It's just that which needs updating as far as I can tell, the appveyor badge in the readme is relevant to the repo's github location instead.

**Comment by rprouse** [comment]
I have updated the webhooks to the URI you provided.

**Comment by ChrisMaddock** [comment]
Hmm, that's annoying - the historical links don't work. I thought they might update with the new source. Never mind - at least it'll be good for the future.
