### ISSUE TITLE
Additional .addins files should be excluded from zip build

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-distribution#17]
The zip is ending up with multiple `.addins` files. There is a static nunit.engine.addins file in this repo, which should be copied in, and there should be no others.

Additional `.addin` files are being copied in from the NUnit.ConsoleRunner and NUnit V2 Framework Driver packages. The line in the build script which copies all contents of a NuGet file into the zip directory should exclude any `.addin` files it finds.

**Comment by CharliePoole** [comment]
I haven't actually looked at the code for creating the zip for a while, so this comment may be extraneous...

In merging all the nuget extensions into a single zip package, I can imagine three ways to go:

1. Create a single `.addins` file in the engine directory and point to each extension by relative path and file name. No other `.addins` files are needed.

2. Create  single `.addins` file in the engine directory with only one entry: "addins/". This takes the engine to the addins directory. The addins directory then contains either a single `.addins` file that you create or a separate `.addins` file for each extension. If the files are separate, you can copy any you find and create all the rest yourself.

3. Create a separate directory for each extension and copy the contents of tools to that directory for each. Create your own `.addins` file in the engine directory with a line for each of the directories you create. Remember to add '/' to indicate the line is a directory.

Hope this gives more of a picture of what's needed. It seems like (1) is simplest right now but one of the others may work better if we later want to make it more automatic.

**Comment by ChrisMaddock** [comment]
Option 1 is what we currently have - which is just reused from the msi. (And also pre-dates the nunit-distribution repository, from back when everything was in the single nunit repository.)

This is simply a bug that the additional `.addins` files from the NuGet packages have been inadvertently copied in. We could of course rewrite things in one of the other ways (a `.addins` file which didn't need manually updating would be nice, one day!) - but I think that's perhaps a separate issue from the simple fix needed here. 🙂
