### ISSUE TITLE
Win10 can't locate .NET Framework prerequisites

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-distribution#18]
@ipavlu commented on [Tue Jun 13 2017](https://github.com/nunit/nunit-console/issues/240)

Hi, please drop damned prerequisites testing from MSI package, it does not understand Win10 with built in .Net...

.Net 2.0, 3.5, 4.0 are all present on the machine, just not explicitly, tehre are not even features on win10 that could be enabled as netfx4. It is really incorrect test...

---

@jnm2 commented on [Tue Jun 13 2017](https://github.com/nunit/nunit-console/issues/240#issuecomment-308266269)

Dunno if this is related, but .Net 2.0 though 3.5 are not present on Win10 until you explicitly install them via 'Turn Windows features on or off.'

---

@ChrisMaddock commented on [Wed Jun 14 2017](https://github.com/nunit/nunit-console/issues/240#issuecomment-308368978)

I'll move this to the nunit-distribution repo, where the msi is currently built, and comment further there.

**Comment by ChrisMaddock** [comment]
We currently check that one of .NET 2.0, 4.0 or Mono is installed. I know there's an element of backwards compatibility in the 4.0 check for later versions of .NET, but I don't know off the top of head what's different in Win 10.

This has come up before. I'm not sure why we read the registry keys ourselves, rather than using the WixNetFxExtension as WiX would recommend, and outsource this bit of maintenance to WiX. http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/check_for_dotnet.html

Alternatively, we could drop the check completely, as @ipavlu suggests - but fixing it to work seems like the preferable solution.

**Comment by CharliePoole** [comment]
Easy answer. We've been using WiX for many years. You used to have to do this stuff yourself.
